### ISSUE TITLE
Some paths are missing

### ISSUE THREAD

**Issue by q4osteam** [seb3773/Q4OSseb#1]
We have checked the scripts, they are really fine. The "qtheme.sh" script even works on i386 architecture, we only needed to create some target directories manually "mkdir -p". The installation log file is attached, you can see the log with "cat qtheme1.log", so you can see missing directories messages.
[qtheme1.log](https://github.com/seb3773/Q4OSseb/files/13404600/qtheme1.log)

**Comment by seb3773** [comment]
Thank you, I think it's ok now. (tell me if it's not :p  )
I added some more icons, and corrected some other little problems (colors not correct in the gtk css)

**Comment by q4osteam** [comment]
Almost fixed, however one error still occurs for folder /root/.trinity/share/apps/tdedisplay/color-schemes
[qtheme.log](https://github.com/seb3773/Q4OSseb/files/13412997/qtheme.log)

**Comment by seb3773** [comment]
hopefully fixed now :)

**Comment by q4osteam** [comment]
Yes, the installation went without error messages :) closing.
