### ISSUE TITLE
Errors running qtheme.sh

### ISSUE THREAD

**Issue by q4osteam** [seb3773/Q4OSseb#10]
Running the latest qtheme.sh on a clean Q4OS installation gives errors, see the log attached.
[qthemesh.log](https://github.com/seb3773/Q4OSseb/files/13546267/qthemesh.log)

**Comment by seb3773** [comment]
I didn't realize $USER_HOME/.local/share/desktop-directories doesn't exist on a fresh install, my fault, I forgot to test the last version on a fresh install. It should be ok now :)

**Comment by q4osteam** [comment]
We can confirm the installation goes fine now.
