### ISSUE TITLE
question to q4osteam - No Qtcurve for Q4OS 32bits ?

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#11]
I finally tried my scripts on a 32bits installation of Q4OS Aquarius, and noticed for the qtheme.sh script that there was no Qtcurve style available by default on the 32bits version. I tried to compile tde-trinity-qtcurve, well, successfully I think, but after a 'make install' and even a reboot the style isn't available in the style config windows. 
So: is it 'normal' that qtcurve isn't available in 32bit version ? And secondly, can we install it anyway and if yes, how ?...
I'm not so personnally interested in making my scripts work with the 32bits version, still, it may be of interest for some people, and it will look better with the qtcurve style :)

**Comment by q4osteam** [comment]
You only need to install it:
$ sudo apt install tde-style-qtcurve-trinity

**Comment by seb3773** [comment]
Ho sorry, didn't know it was available like that, didn't found it in synaptic when I searched. Thank you, script updated :)
