### ISSUE TITLE
question to q4osteam - kicker menu kside.png image color

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#13]
In the new version of the qtheme.sh script, you can now specify a custom color for what I call the 'accent' color; for example
run 'qtheme.sh -c' and choose an accent color  (this color will be applied to windows decorations, kicker & menu background+kside images and other parts.)
It seems to work ok, but the kside.png/kside_tile.png images generated with the accent color are displayed in gray level or something like that, but not the images color. Is there a parameter somewhere that apply a tint or something like that to these images ?

**Comment by q4osteam** [comment]
As far as we know, this is not customisable. You could check the file in tdebase source code > tdebase-trinity-14.1.1/kicker/libkicker/kickerSettings.kcfg for all possible options for kside.

**Comment by seb3773** [comment]
Found it :)
It is colorized depending for example of the windows titlebar color.

found it here: in k_mnu.cpp:
    KickerLib::colorize(image);
    sidePixmap.convertFromImage(image);
    
and in global cpp we have it:
void colorize(TQImage& image)
{
    TDEConfig *config = TDEGlobal::config();
    config->setGroup("WM");
    TQColor color = TQApplication::palette().active().highlight();
    TQColor activeTitle = config->readColorEntry("activeBackground", &color);
    TQColor inactiveTitle = config->readColorEntry("inactiveBackground", &color);

    // figure out which color is most suitable for recoloring to
    int h1, s1, v1, h2, s2, v2, h3, s3, v3;
    activeTitle.hsv(&h1, &s1, &v1);
    inactiveTitle.hsv(&h2, &s2, &v2);
    TQApplication::palette().active().background().hsv(&h3, &s3, &v3);

    if ( (kAbs(h1-h3)+kAbs(s1-s3)+kAbs(v1-v3) < kAbs(h2-h3)+kAbs(s2-s3)+kAbs(v2-v3)) &&
            ((kAbs(h1-h3)+kAbs(s1-s3)+kAbs(v1-v3) < 32) || (s1 < 32)) && (s2 > s1))
        color = inactiveTitle;
    else
        color = activeTitle;

    // limit max/min brightness
    int r, g, b;
    color.rgb(&r, &g, &b);
    int gray = tqGray(r, g, b);
    if (gray > 180) {
        r = (r - (gray - 180) < 0 ? 0 : r - (gray - 180));
        g = (g - (gray - 180) < 0 ? 0 : g - (gray - 180));
        b = (b - (gray - 180) < 0 ? 0 : b - (gray - 180));
    } else if (gray < 76) {
        r = (r + (76 - gray) > 255 ? 255 : r + (76 - gray));
        g = (g + (76 - gray) > 255 ? 255 : g + (76 - gray));
        b = (b + (76 - gray) > 255 ? 255 : b + (76 - gray));
    }
    color.setRgb(r, g, b);
    TDEIconEffect::colorize(image, color, 1.0);
}

So I only need to figure how to generate a grayscale image who will give the nearest original color once colorized with this method.. Not trivial, but feasible I think. Will work on it :)

**Comment by q4osteam** [comment]
Yes, it should be possible to add an option not to colorize the kside image. Would you want us to work on that ?

**Comment by seb3773** [comment]
This could be very cool :) I have made an approximation of the gray level to use depending of the color choosed but it's far from perfect (will upload it soon with some modifications/improvements). This is a little thing, but I think the theme will be more credible/aesthetic with a kside image the same color as the menu... So yes :)  if you can do it, I would really appreciate it :)

**Comment by q4osteam** [comment]
We have compiled Trinity experimental packages. Download, extract the archive, make local repository and update as usual https://sourceforge.net/projects/q4os/files/experimental_packages/kmenu_debs_14.1.1-0debian12.0.0+0.1-kmenutest.2.tar.gz

**Comment by seb3773** [comment]
wow that was fast :) :)  thank you very much !
New version uploaded, who use this option :) (of course it looks much better than with my previous approximation of the grey scale to use ^^)
Custom color option added too in qmenu for easier access :)
