### ISSUE TITLE
Tip: sample kicker applet build

### ISSUE THREAD

**Issue by q4osteam** [seb3773/Q4OSseb#14]
After all we have compile a package for you to be able to build the sample kicker applet from source. Just extract the archive and run "$ sh autogen.sh" script. It will do the complete build and even create a .deb package with of the sample applet.
[kicker_applet_sample.tar.gz](https://github.com/seb3773/Q4OSseb/files/13683805/kicker_applet_sample.tar.gz)

If you have any questions just ask here :)

**Comment by seb3773** [comment]
Ho ! Good news, so much thanks :) will try it asap

**Comment by seb3773** [comment]
Ok, now I can compile project and make changes :) thank you ! I started to work on it.
Just a little problem, it can't install the files created, but I found a workaround by copying them manually.

----------------------------------------------------------------------
 /usr/bin/mkdir -p '/opt/trinity/share/apps/kicker/applets'
 /usr/bin/install -c -p -m 644 kicker_applet_sample.desktop '/opt/trinity/share/apps/kicker/applets'
/usr/bin/install: impossible de créer le fichier standard '/opt/trinity/share/apps/kicker/applets/kicker_applet_sample.desktop': Aucun fichier ou dossier de ce type
make[2]: *** [Makefile:647 : install-kicker_applet_sampleDATA] Erreur 1
make[2] : on quitte le répertoire « /home/cdef/kicker_applet_sample/src »
make[1]: *** [Makefile:764 : install-am] Erreur 2
make[1] : on quitte le répertoire « /home/cdef/kicker_applet_sample/src »
make: *** [Makefile:582 : install-recursive] Erreur 1

****  Installation failed. Aborting package creation.

**Comment by q4osteam** [comment]
Try to create the destination folder manually
$ sudo mkdir -p /opt/trinity/share/apps/kicker/applets/
and run installation once again.

**Comment by seb3773** [comment]
Unfortunately same error ( destination folder already exist by the way)...

**Comment by seb3773** [comment]
It seems a bit more complicated than I thought to 'integrate' the code found in showdesktop.cpp/showdesktop.h in a new applet... I think I understand how it works, although no success yet in compiling a working version

**Comment by seb3773** [comment]
Well, I finally did it :) My code is working, and it has the desired behavior :) Now, I would want to rename the applet/project/libs to something more comprehensible, like 'ShowDesk10', but I have some difficulties doing it. Maybe I can paste the .cpp & .h code and you can help me to create a new project like you did with kicker_applet_sample   ?

**Comment by q4osteam** [comment]
Great you have advanced. We don't understand exactly what you need. If you want rename the project, just browse the code and rename all old-name strings. Moreover, made renames in files and directories names. Of course, you paste the code here for a review.

**Comment by q4osteam** [comment]
You could make a separate ShowDesktop project on Github, so we can contribute to it.

**Comment by seb3773** [comment]
Of course, will do it :)
