### ISSUE TITLE
Desktop doesn't respond properly

### ISSUE THREAD

**Issue by q4osteam** [seb3773/Q4OSseb#16]
Desktop seems not to respond properly after qtheme.sh installation. Reproduce:
- Install Q4OS Trinity in Vritualbox, basic profile
- Run qtheme.sh, reboot, login
- Various desktop actions doesn't work
- Run konsole, for example, and try to type. No echo returned.

**Comment by seb3773** [comment]
I think I found the bug, please try the new version and tell me if it's ok for you :)

**Comment by q4osteam** [comment]
We can confirm, the latest update solved the issue.
