### ISSUE TITLE
question to q4osteam - using something else than Q4OS02 folder

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#18]
I think overwriting the Q4OS02 folder is not a very good idea, and that I need to create a specific theme folder like "Q4OSWIN10" for example. What do you think ? (so it will 'survive' to updates)

**Comment by q4osteam** [comment]
It's not clear what Q4OS02 folder do you mean, please specify. Yes, overwriting is not a good idea in general, besides other things updates would revert the folder content back.

**Comment by seb3773** [comment]
I was talking about the theme folder "Q4OS02", I'm working on using another folder now :)
