### ISSUE TITLE
question to Q4osteam - enabling compositing from command line

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#19]
I can't find where and how compositing is enabled... It doesn't seem to be stored in a config file ?

I want to enable compositing (tdecompton) like we can do in the graphical interface:
![ksnapshotHrbk0d](https://github.com/seb3773/Q4OSseb/assets/99963207/44af4433-c179-4607-96bf-1c0b0c337605)

**Comment by q4osteam** [comment]
Check the script /usr/bin/ctrl-compmgr , so can determine config files used.

**Comment by seb3773** [comment]
It's ok now :) Thank you ! 
By the way, I had already activated this in the past, but this was causing freezing/unresponsive desktop. In fact, these bugs were only presents in virtualbox and I found that you need to activate 3D video & 128Mb or video ram for the virtual machine :)

**Comment by q4osteam** [comment]
Great you figure that out. However something doesn't go the right way as plain Q4OS installation with compositing enabled works fine in Virtualbox with that specs.

**Comment by seb3773** [comment]
Yes, I will try to find out why. I suspect it's maybe the modifications I made to .compton-tde.conf.
I tried to tweak it with suggestions I found on the web, but maybe I screwed up something...
My .compton-tde.conf file content:

shadow = true;
shadow-offset-y = -126;
shadow-offset-x = -126;
shadow-red = 0.35;
shadow-green = 0.35;
shadow-blue = 0.35;
shadow-radius = 5;
fading = true;
no-fading-opacitychange = false;
no-fading-openclose = false;



wintypes:
{
  menu = { shadow = false; fade = true; no-fading-openclose = false; };
  dropdown_menu = { shadow = true; fade = true; no-fading-openclose = false; };
  popup_menu = { shadow = true; fade = true; no-fading-openclose = false; };
  tooltip = { shadow = false; fade = true; no-fading-openclose = false; };
  normal = { shadow = true; fade = true; no-fading-openclose = false; };
  dialog = { shadow = true; fade = true; no-fading-openclose = false; };
  unknown = { shadow = true; fade = true; no-fading-openclose = false; };
  toolbar = { shadow = true; fade = true; no-fading-openclose = false; };
  utility = { shadow = true; fade = true; no-fading-openclose = false; };
  splash = { shadow = true; fade = true; no-fading-openclose = false; };
  notify = { shadow = false; fade = true; no-fading-openclose = false; };
  combo = { shadow = false; fade = true; no-fading-openclose = false; };
  desktop = { shadow = false; fade = true; no-fading-openclose = false; };
  dnd = { shadow = false; fade = true; no-fading-openclose = false; };
  dock = { shadow = true; fade = true; no-fading-openclose = false; };
};
fade-in-step = 0.08;
fade-out-step = 0.08;
backend = "glx";
paint-on-overlay = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = "opengl-swc";
blur-background = false;
blur-background-fixed = true;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow-exclude = [
  "n:e:Notification",
  "n:w:*Firefox*",
  "n:w:*google-chrome*",
  "n:w:*kicker*"
];


greyscale-background = false;
no-dock-shadow = false;
no-dnd-shadow = true;
clear-shadow = true;
shadow-ignore-shaped = true;

.....
I think maybe this part:
backend = "glx";
paint-on-overlay = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = "opengl-swc";

who differs from the original. (xrender initially I think, need to check)
