### ISSUE TITLE
request_q4osteam - (high priority) /  custom color for the classic Kicker menu background

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#2]
It will be of great help if we could set a color for the TDEmenu background, independently of the general windows background color.
Maybe something like LegacyKMenuBackgroundColor=(x,x,x) in kickerrc ? Or maybe just use the TintColor setting ?

**Comment by q4osteam** [comment]
We definitely need to modify TDE source code, however it should be possible. We are going to work on that, so please create a new bug report as a request for Q4OS devs https://sourceforge.net/p/q4os/tickets/ , so we can track this one.

**Comment by q4osteam** [comment]
We have already created new bug report at Q4OS tracker https://sourceforge.net/p/q4os/tickets/219/

**Comment by seb3773** [comment]
By the way, I don't know how is the code, but maybe it's possible to achieve the same thing that's done with the taskbar ? I mean color tint & transparency+blurred background ? It will be be very good looking ;)

**Comment by q4osteam** [comment]
We have compiled testing Trinity libraries with modified source code to enable Kmenu custom colors.
- First you need to download testing packages https://sourceforge.net/projects/q4os/files/experimental_packages/kmenu_debs_14.1.1-0debian12.0.0%2B0.1-kmenutest.1.tgz/download
- Extract the archive to a local directory.
- You need to create local Apt repository, see https://askubuntu.com/questions/170348/how-to-create-a-local-apt-repository
- Do system upgrade. A few Trinity packages will be upgraded to the "14.1.1-0debian12.0.0+0.1-kmenutest.1" versions.
- Configure the desired Kmenu background color, for example green:
  $ /opt/trinity/bin/kwriteconfig --file kickerrc --group KMenu --key ClassicKMenuBackgroundColor 0,255,0
- Reboot and see what happens.

**Comment by q4osteam** [comment]
Yes, we can include these modifications in the official release in the future, however it will take some more testing and making it stable.

**Comment by seb3773** [comment]
Ok, I understand :)
I have installed the packages on two computers with Q4OS, my old N3060 celeron laptop and my more recent i3 gen11 desktop. As Q4OS is now definitly my main OS, I can inform you if I find any bugs or stability problems with it, if it can be usefull for you.
May be we can keep this issue open for that ?

**Comment by q4osteam** [comment]
Reporting would be definitely helpful. Yes, keep the thread open.

**Comment by seb3773** [comment]
No problem so far :) Tested it a lot, it works well and no side effects. Hope this improvement will be integrated in official releases :)
Thank you again for that.
