### ISSUE TITLE
request_q4osteam (normal priority) / Redmond Ksplash modifications

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#4]
Is it possible to remove the "Welcome" message & user icon, and just keep the user name & trinity messages  ?

**Comment by q4osteam** [comment]
Just edit the file "/opt/trinity/share/apps/ksplash/Themes/Redmond/Theme.rc" and add lines "Show Welcome Text=false" and "Show Icon = false" 
You can modify quite a lot of splash screen parameters in that file, see the "/opt/trinity/share/doc/tde/HTML/en/ksplashml/index.docbook" , even it's possible to define user level configuration.

**Comment by q4osteam** [comment]
Redmond engine likely doesn't support all the options. You can check Redmond options in the source file "ksplashml/themeengine/redmond/themeredmond.cpp" in the tdebase source code https://sourceforge.net/projects/q4os/files/experimental_packages/tdebase-trinity-14.1.1.tar.gz/download

**Comment by seb3773** [comment]
thank you :)

**Comment by seb3773** [comment]
Thank you, issue closed :)
