### ISSUE TITLE
question to q4osteam - vlc doesn't follow theme colors

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#6]
I noticed vlc doesn't seem to follow theme colors, this is visible in the dark theme, some colors stays white and some text part are difficults to read. I know there's a way to fix it by replacing  q4ostde with qt5ct, but somewhere in the Q4OS forum you said it's not a good idea because it may break things if it is used instead of q4ostde.
I know there's somekind of a solution, keeping q4ostde the default and using qt5ct ENV to launch vlc or other qt5 apps, for example by adding the appropriate env  QT_QPA_PLATFORMTHEME, for example:

env QT_QPA_PLATFORMTHEME=qt5ct /usr/bin/vlc --started-from-file %U

But it's not very elegant/practical to loop through the .desktop files and changing what's need to be adjusted... Do you know a way to fix it more elegantly ?

**Comment by q4osteam** [comment]
No easy solution is now available as far as we know. q4ostde style tries to pass as much as possible of TDE settings to QT5 apps, however it's not perfect, as you can see in vlc player. So we need to improve the q4ostde style, it's long time run as we are working on that.

A possible workaround with drawback would be setting another QT5 style globally by setting QT_QPA_PLATFORMTHEME variable in "/opt/trinity/env/50_q4loginscr01.sh" for all applications, but you will loose q4ostde style functionality.

**Comment by q4osteam** [comment]
You could also describe the vlc issue and create a new bug report for Q4OS developers https://sourceforge.net/p/q4os/tickets/ , so we could track and discuss this one separately at the bug tracker.

**Comment by seb3773** [comment]
I understand. I will create a new bug report like you said :)

**Comment by q4osteam** [comment]
The bug is now fixed, update from repositories is sufficient to get the fix.

**Comment by seb3773** [comment]
I confirm it's fixed on my side :) Thank you very much !
