### ISSUE TITLE
question to q4osteam - detect usb device insertion/removal ?

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#8]
It's one little thing, but it would be cool (& usefull) : how can we detect usb device insertion/removal (in order to play a sound for this action )? It will be usefull to have a sound notification for this I think, and it will be more "windows" like :)
(I try a bit with udev but I think there's already a detection mechanism in Q4os, because it can present a windows with available actions for usb storage for example.)

**Comment by q4osteam** [comment]
We are not aware of some quick solution at the moment, however it may exist. You could also try > control panel > peripherals > storage media > notifications tab > add an action for unmounted medium insertion > specify command to play a sound, for example "artsplay <sound_file>"

**Comment by seb3773** [comment]
I think I found the solution :) I updated the scripts if you want to try :)
How I did it:
- created a new rule file in  /etc/udev/rules.d with this content:
SUBSYSTEM=="usb", ACTION=="add", ENV{DEVTYPE}=="usb_device", RUN+="/usr/bin/usb_insert"
SUBSYSTEM=="usb", ACTION=="remove", ENV{DEVTYPE}=="usb_device", RUN+="/usr/bin/aplay -N /opt/trinity/share/sounds/device-removed.wav"


. The reason I don't use "usr/bin/aplay -N /opt/trinity/share/sounds/device-added.wav" in the first line is because it triggers the sound during the startup, before the login screen. I don't want that so I test if a user is connected, if not, no sound is played.
usb-insert is just a simple program in c++ that achieve that, but we can use a bash script too, something like thatwill do the trick for example:

#!/bin/bash
if w | grep -q starttde; then /usr/bin/aplay -Nq /opt/trinity/share/sounds/device-added.wav &
fi

(by the way I don't what is "better", using a bash script or a little binary ?.. Anyway I don't think one or the other has a real impact the performance)

**Comment by q4osteam** [comment]
Yes, the performance impact is negligible. We would suggest to close this report as resolved.
