### ISSUE TITLE
question to q4osteam - kicker applet coding ?

### ISSUE THREAD

**Issue by seb3773** [seb3773/Q4OSseb#9]
Is it possible to code an applet for the kicker ? And if it's possible, can you guide me a bit ?... (maybe the source code of an existing applet and directions to compile/install ?) . I can code in C, but don't really know where to start.
(my idea is coding a very simple applet like the existing 'show desktop' one, but 'ala windows10', in the extreme right of the taskbar)

thanks by advance

**Comment by q4osteam** [comment]
Yes, it's possible definitely. You may start installing kdevelop-trinity package, run "tdevelop c/c++" from menu,create new project and check projects templates for an applet template. Please feed a result back, if you will have more particular questions, we will try to answer.

**Comment by seb3773** [comment]
thank you, I installed tdevelop-trinity, where can I find an existing applet source code somewhere (or better maybe, the existing showdesktop applet source code ) to have an example ?

**Comment by q4osteam** [comment]
Run tdevelop > create a new project from template > templates window dialog opens, search for "kicker applet template" > create the project > you will find source code in the directory where you point the project to create to.
![snapshot5](https://github.com/seb3773/Q4OSseb/assets/16801039/1053f9a8-9a0c-4655-a210-adfa0de7a30c)

**Comment by seb3773** [comment]
Understood, thank you :) May I ask if it's possible to find the source code of some existing applets like the ShowDesktop one ?...

**Comment by q4osteam** [comment]
ShowDesktop is a part of Tdebase core, so we share the source code https://sourceforge.net/projects/q4os/files/experimental_packages/tdebase-trinity-14.1.1.tar.gz/download . Download, unpack the source archive, you will find ShowDesktop source in "kicker/kicker/core/showdesktop.cpp" . Other various applets are in "kicker/applets/" directory.

**Comment by seb3773** [comment]
Thank you very much !!!

**Comment by seb3773** [comment]
I tried to build a simple applet, but I have this error:
Compilation showde10.cpp (g++)
*** Sortie avec l'état : 2 ***

It's the applet template (who should display 42 and does nothing special if I understand correctly the existing code).
Is there something else I need to do ? (except configure/automake)
Sorry if it's a silly question

**Comment by q4osteam** [comment]
Not a silly question :) Would you provide more of the compilation log ? How do you compile the example, in terminal or in tdevelop ide ?

**Comment by seb3773** [comment]
Thank you very much :) It compiles without errors. It generates libkicker_applet_sample.so.1.0.0 and 3 symlinked files, the next step is to copy them to /opt/trinity/lib/ ? Didn't I have to create something like a .desktop file in /opt/trinity/share/apps/kicker/applets ?..

**Comment by q4osteam** [comment]
After a quick check, a proper building of the kicker applet template seems to be more complicated to us. At this point we would recommend you to post a new issue for TDE developers, so they fix tdevelop templates as it's impossible to build and apply them https://mirror.git.trinitydesktop.org/gitea/TDE

**Comment by seb3773** [comment]
I understand, too bad for now ... I will try to post a new issue for tde developpers. thank you for your time :)
